var seatList1 = [
  {
    rowName: 'A',
    price: 420,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: false },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'B',
    price: 420,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'C',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true },
      { seatNo: 23, booked: false, available: false },
      { seatNo: 24, booked: false, available: true },
      { seatNo: 25, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'D',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: false },
      { seatNo: 22, booked: false, available: true },
      { seatNo: 23, booked: false, available: true },
      { seatNo: 24, booked: false, available: true },
      { seatNo: 25, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'E',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'F',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'G',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'H',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'I',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'J',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'K',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'L',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'M',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true }
    ],
    type: 'Recliner'
  }
];
var seatList2 = [
  {
    rowName: 'B',
    price: 420,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: false },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'E',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true },
      { seatNo: 23, booked: false, available: false },
      { seatNo: 24, booked: false, available: true },
      { seatNo: 25, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'F',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: false },
      { seatNo: 22, booked: false, available: true },
      { seatNo: 23, booked: false, available: true },
      { seatNo: 24, booked: false, available: true },
      { seatNo: 25, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'G',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'H',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: false },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: false },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: false },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: false },
      { seatNo: 22, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'I',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: false },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: false },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: false },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: false },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'J',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: false },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'K',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: false },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: false },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: false },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: false },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'L',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: false },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: false },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'M',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: false },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: false },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'N',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: false },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'O',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true }
    ],
    type: 'Recliner'
  }
];
var seatList3 = [
  {
    rowName: 'F',
    price: 420,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: false },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'G',
    price: 420,
    seatList: [
      { seatNo: 1, booked: false, available: false },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: false },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: false },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: false },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: false },
      { seatNo: 14, booked: false, available: false },
      { seatNo: 15, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'C',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: false },
      { seatNo: 4, booked: false, available: false },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: false },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: false },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: false },
      { seatNo: 14, booked: false, available: false },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: false },
      { seatNo: 20, booked: false, available: false },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'D',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: false },
      { seatNo: 5, booked: false, available: false },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: false },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: false },
      { seatNo: 12, booked: false, available: false },
      { seatNo: 13, booked: false, available: false },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: false },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: false },
      { seatNo: 22, booked: false, available: true },
      { seatNo: 23, booked: false, available: false }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'E',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: false },
      { seatNo: 5, booked: false, available: false },
      { seatNo: 6, booked: false, available: false },
      { seatNo: 7, booked: false, available: false },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'F',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'G',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'H',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'I',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'J',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'K',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'L',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true },
      { seatNo: 20, booked: false, available: true },
      { seatNo: 21, booked: false, available: true },
      { seatNo: 22, booked: false, available: true }
    ],
    type: 'Recliner'
  },
  {
    rowName: 'M',
    price: 250,
    seatList: [
      { seatNo: 1, booked: false, available: true },
      { seatNo: 2, booked: false, available: true },
      { seatNo: 3, booked: false, available: true },
      { seatNo: 4, booked: false, available: true },
      { seatNo: 5, booked: false, available: true },
      { seatNo: 6, booked: false, available: true },
      { seatNo: 7, booked: false, available: true },
      { seatNo: 8, booked: false, available: true },
      { seatNo: 9, booked: false, available: true },
      { seatNo: 10, booked: false, available: true },
      { seatNo: 11, booked: false, available: true },
      { seatNo: 12, booked: false, available: true },
      { seatNo: 13, booked: false, available: true },
      { seatNo: 14, booked: false, available: true },
      { seatNo: 15, booked: false, available: true },
      { seatNo: 16, booked: false, available: true },
      { seatNo: 17, booked: false, available: true },
      { seatNo: 18, booked: false, available: true },
      { seatNo: 19, booked: false, available: true }
    ],
    type: 'Recliner'
  }
];

var seatList = [seatList1, seatList2, seatList3];
module.exports.seatList = seatList;